FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend .

# Añadir el directorio actual (/app) al PYTHONPATH
ENV PYTHONPATH=/app

# CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["sh", "-c", "python scripts/init_load.py && uvicorn api.main:app --host 0.0.0.0 --port 8000"]
